server : 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto : ${SPRING_JPA_HIBERNATE_DLL_AUTO:update}
      show-sql : ${SPRING_JPA_HIBERNATE_SHOW_SQL:true}
    properties:
      hibernate:
        dialect : ${SPRING_JPA_HIBERNATE_DIALECT}